name: Deploy Yolo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_INSTANCE_SSH_KEY }}
          script: |
            cd ~/polyAIFursa
            git pull origin dev
            source .venv/bin/activate
            pip install -r services/yolo/torch-requirements.txt
            pip install -r services/yolo/requirements.txt
            pip install -r services/agent/requirements.txt
            cd services/frontend
            npm install
            npm run build
            cd ../..
            sudo systemctl restart yolo.service
            sudo systemctl restart agent.service
            sudo systemctl restart frontend.service
            sudo systemctl status yolo.service --no-pager
            sudo systemctl status agent.service --no-pager
            sudo systemctl status frontend.service --no-pager

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.PROD_INSTANCE_SSH_KEY }}
          script: |
            cd ~/polyAIFursa
            git pull origin main
            source .venv/bin/activate
            pip install -r services/yolo/torch-requirements.txt
            pip install -r services/yolo/requirements.txt
            pip install -r services/agent/requirements.txt
            cd services/frontend
            npm install
            npm run build
            cd ../..
            sudo systemctl restart yolo.service
            sudo systemctl restart agent.service
            sudo systemctl restart frontend.service
            sudo systemctl status yolo.service --no-pager
            sudo systemctl status agent.service --no-pager
            sudo systemctl status frontend.service --no-pager